Fix local failure of tests/test_logging.py::test_log_formatting
Running the test locally caused:
```
    @freeze_time("2023-05-05 11:11:11")
    def test_log_formatting(snapshot):
        logger = logging.getLogger("inclusion_connect")  # Root logger for IC.
        [handler] = logger.handlers
        with io.StringIO() as capture_stream:
            handler.setStream(capture_stream)
            logger.info({"key": "value", "other_key": "value"})
>           assert capture_stream.getvalue() == snapshot(name="log serialized as JSON with metadata")
E           assert [+ received] == [- snapshot]
E               '''
E               {"key": "value", "other_key": "value", "@timestamp": "2023-05-05T11:11:11Z", "name": "inclusion_connect", "level
name": "INFO"}
E             - INFO:inclusion_connect:{'key': 'value', 'other_key': 'value'}
E
E               '''
```

```
INFO:inclusion_connect:{'key': 'value', 'other_key': 'value'}
```
is only present when the environment variable `POSTGRESQL_ADDON_URI` is
missing. That’s because dj-database-url uses logging.warning() [1] to
warn when its database URL variable is missing. That installs a default
handler on the root logger, and that default handler writes to the
console. When the variable is defined, the warning is not issued and the
logging module does not configure the root handler.

[1] https://github.com/jazzband/dj-database-url/blob/86f04ef5c6dac24764af73068b80655d7b26510c/dj_database_url/__init__.py#L69